AWSTemplateFormatVersion: '2010-09-09'
Description: flows charts
Resources:
  piechartFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: mesh-plugin-prod-artifacts
        S3Key: 90b41e00c6c50c4fc4ee54e671845380
      Handler: index.handler
      Role:
        Fn::GetAtt:
        - LambdaRole
        - Arn
      Runtime: nodejs8.10
      Timeout: 300
  piechartLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        Fn::Sub: /aws/lambda/${piechartFunction}
      RetentionInDays: 7
  stackedareachartFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: mesh-plugin-prod-artifacts
        S3Key: 79a71f22d31da233bd05dc8eca993439
      Handler: index.handler
      Role:
        Fn::GetAtt:
        - LambdaRole
        - Arn
      Runtime: nodejs8.10
      Timeout: 300
  stackedareachartLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        Fn::Sub: /aws/lambda/${stackedareachartFunction}
      RetentionInDays: 7
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: /
      Policies:
      - PolicyName: LambdaRolePolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource: arn:aws:logs:*:*:*
  InvokeRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            AWS:
            - 184705290838
          Action:
          - sts:AssumeRole
      Path: /
      Policies:
      - PolicyName: LambdaRolePolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - lambda:InvokeFunction
            Resource:
            - Fn::GetAtt:
              - piechartFunction
              - Arn
            - Fn::GetAtt:
              - stackedareachartFunction
              - Arn
Outputs:
  piechartFunction:
    Description: piechart
    Value:
      Fn::GetAtt:
      - piechartFunction
      - Arn
  piechartRole:
    Description: piechart
    Value:
      Fn::GetAtt:
      - InvokeRole
      - Arn
  stackedareachartFunction:
    Description: stackedareachart
    Value:
      Fn::GetAtt:
      - stackedareachartFunction
      - Arn
  stackedareachartRole:
    Description: stackedareachart
    Value:
      Fn::GetAtt:
      - InvokeRole
      - Arn
